---
- name: Install python master node
  hosts: hadoop-master
  remote_user: ubuntu
  become: yes
  gather_facts: False

  tasks:
  - name: Install python
    raw: test -e /usr/bin/python || (apt-get install -y python3 python-simplejson)

- name: Install hadoop master node
  hosts: hadoop-master
  remote_user: ubuntu
  become: yes

  roles:
    - common
    - oraclejava8
    - master

- name: Install hadoop data nodes
  hosts: hadoop-data
  remote_user: ubuntu
  become: yes

  roles:
    - common
    - oraclejava8
#    - data
